### ISSUE TITLE
volumetric speed

### ISSUE THREAD

**Issue by supermerill** [AndrewEllis93/Ellis-PIF-Profile#10]
Hi
I have detected a little error
when you say

> The volumetric speed limit controls the maximum rate that your hotend is allowed to extrude.
>
>No matter how much you push speeds, layer heights, or line widths, it will never allow you to outrun your hotend.

But in the picture, it's the (max) flow for the auto-speed feature (when a speed is set to 0). 
The universal flow limit you talk about is in the filament tab.

**Comment by AndrewEllis93** [comment]
My understanding was that the flow in the filament tab just overrides that setting if a particular filament acts differently. 

When I change the number in the print settings, it does seem to apply 

![image](https://user-images.githubusercontent.com/34943186/180826955-87bc8522-b035-4620-855c-dff99cf91734.png)
![image](https://user-images.githubusercontent.com/34943186/180826962-a3bc40b3-37a6-482c-bc35-39ef69feed06.png)

**Comment by supermerill** [comment]
Dang, you're right.
I modified it a year ago and forgot to save it in my brain.
I'll modify the tooltip to reflect the behavior.

**Comment by dewi-ny-je** [comment]
And yet it's likely a good idea to tell people to put that limitation in the filament tab: PLA and ABS have quite different flow limits for a given extruder/hotend.

Also, maybe a couple of tips about different nozzles: I use different filament settings ("PLA 0.6", "PLA 0.4") so that each one can have a different flow limit. 
Obviously I also have multiple "printer" profiles for the nozzles.
